extensions:
  headers_setter:
    headers:
      - action: insert
        key: oneuptime-service-token
        from_context: oneuptime-service-token

processors:

receivers:
  otlp:
    protocols:
      grpc:
      http:
        include_metadata: true



exporters:
  otlphttp:
    endpoint: "http://ingestor:3400/otel"
    headers: {"Content-Type": "application/json"}

service:
  extensions: [ headers_setter ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]