name: Compile

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   
      - 'release'


jobs:

  compile-accounts:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd Accounts && npm install && npm run compile && npm run dep-check

  compile-api-reference:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd ApiReference && npm install && npm run compile && npm run dep-check

  compile-common-server:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install && npm run compile && npm run dep-check

  compile-common-ui:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonUI && npm install --force && npm run compile && npm run dep-check

  compile-common:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install && npm run compile && npm run dep-check

  compile-dashboard-api:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd DashboardAPI && npm install && npm run compile && npm run dep-check
  

  compile-admin-dashboard:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd AdminDashboard && npm install && npm run compile && npm run dep-check

  compile-dashboard:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd Dashboard && npm install && npm run compile && npm run dep-check

  compile-file:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd File && npm install && npm run compile && npm run dep-check

  compile-home:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Home && npm install && npm run compile && npm run dep-check

  compile-identity:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Identity && npm install && npm run compile && npm run dep-check


  compile-notification:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Notification && npm install && npm run compile && npm run dep-check

  compile-model:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd Model && npm install && npm run compile && npm run dep-check

  compile-probe:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Probe && npm install && npm run compile && npm run dep-check

  compile-ingestor:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Ingestor && npm install && npm run compile && npm run dep-check
  

  compile-status-page:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd StatusPage && npm install && npm run compile && npm run dep-check

  compile-workers:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd CommonUI && npm install --force
      - run: cd Workers && npm install && npm run compile && npm run dep-check

  compile-workflow:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd Workflow && npm install && npm run compile && npm run dep-check

  compile-test-server:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: cd Common && npm install
      - run: cd Model && npm install
      - run: cd CommonServer && npm install
      - run: cd TestServer && npm install && npm run compile && npm run dep-check